CREATE TABLE IF NOT EXISTS "schema_migrations" (version varchar(128) primary key);
CREATE TABLE note_titles (
  id INTEGER NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  note_id TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE note_bodies (
  id INTEGER NOT NULL PRIMARY KEY,
  body TEXT NOT NULL,
  note_id TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE file_contents_cache (
  id INTEGER NOT NULL PRIMARY KEY,
  content TEXT NOT NULL
);
-- Dbmate schema migrations
INSERT INTO "schema_migrations" (version) VALUES
  ('20241018031041'),
  ('20241018031311'),
  ('20241109063040');
